In [135]:
class LogisticRegression:
    
    def __init__(self, learning_rate=.1, n_iters=10):
        self.lr = learning_rate
        self.n_iters = n_iters
        self.weights = None
        self.bias = None
    
    def fit(self, x, y):
        n_samples, n_features = x.shape
        
        # init parameters
        self.weights = np.zeros(n_features)
        self.bias = 0
        
        # gradient descents
        for _ in range(self.n_iters):
            # approximate y with linear combination of weights and x, plus bias
            linear_model = np.dot(x, self.weights) + self.bias
            # applly sigmoid function
            y_pred = self.sigmoid(linear_model)
            
            # compute gradients
            dw = (1/n_samples) * np.dot(x.T, (y_pred - y))
            db = (1/n_samples) * np.sum(y_pred - y)
            
            # update parameters
            self.weights -= self.lr * dw
            self.bias -= self.lr * db
        return 'data has been train carefully'
    
    def sigmoid(self, z):
        return 1/(1+np.exp(-z))
            
    def predict(self, x):
        linear_model = np.dot(x, self.weights) + self.bias
        y_pred = self.sigmoid(linear_model)
        predicted_class = [1 if i > .5 else 0 for i in y_pred]
        return np.array(predicted_class)
    
    def score(self, y_true, y_pred):
        # accuracy = (TP+TN)/(TP+TN+FP+FN)
        acc = np.sum(y_true==y_pred)/len(y_true)
        return acc

In [20]:
from sklearn.model_selection import train_test_split as split
from sklearn.datasets import load_breast_cancer

In [21]:
df = load_breast_cancer()

In [22]:
x = df.data
y = df.target

In [23]:
x_train, x_test, y_train, y_test = split(x, y, test_size=.2, random_state=1234)

In [140]:
model = LogisticRegression(learning_rate=.0001, n_iters=1000)

In [141]:
model.fit(x_train, y_train)

'data has been train carefully'

In [142]:
model.predict(x_test)

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 0])

In [143]:
model.score(y_test, model.predict(x_test))

0.9298245614035088

In [144]:
y_test

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0])

In [3]:
w = np.array([[1], [6], [2], [4]])

In [4]:
w

array([[1],
       [6],
       [2],
       [4]])

In [5]:
w.shape

(4, 1)

In [6]:
x = np.array([[3, 8, 2, 4], [5, 1, 9, 6], [2, 7, 1, 3]])

In [7]:
x

array([[3, 8, 2, 4],
       [5, 1, 9, 6],
       [2, 7, 1, 3]])

In [8]:
x.shape

(3, 4)

In [13]:
dot_prod = np.dot(w.T, x.T)

In [16]:
sum_prod = np.sum(w.T * x)

In [19]:
dot_prod.shape

(1, 3)

In [18]:
sum_prod

182